mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('orderhelper.urls')),
]

orderhelper/urls.py
from django.conf.urls import patterns, include, url
from . import views
from .views import ProfileView, PendingView, DashboardView, HistoryView, SearchView, PendingSubcomandaCloseView, SubcomandaDetailView, ComandaDetailView, PendingComandaCloseView, PendingComandaCancelView, PendingSubcomandaCancelView, DashboardComandaEditView,DashboardProducatorEditView, DashboardProiectEditView,  DashboardFurnizorEditView, DashboardReperEditView, DashboardSubcomandaEditView, DashboardProiectView,DashboardReperModalView, DashboardFurnizorView, DashboardProducatorView, DashboardReperView, DashboardComandaView, DashboardComandaCreateView, DashboardPersoanaCreateView, DashboardProiectCreateView, DashboardFurnizorCreateView, DashboardProducatorCreateView, DashboardReperCreateView, DashboardSubcomandaCreateView, DashboardSubcomandaView


urlpatterns = [
	
    # url(r'^comanda/(?P<pk>[0-9]+)/$', views.comanda_subcomenzi, name='comanda_subcomenzi'),

    url(r'^$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', views.logout_page, name='logout_page'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),  

    # Pending 
    url(r'^pending/$', PendingView.as_view(), name='pending'),

    # Comanda/Subcomanda urls used Pending & History
    url(r'^subcomanda/close/(?P<pk>\d+)$', PendingSubcomandaCloseView.as_view(), name='pending_subcomanda_close'),
    url(r'^comanda/close/(?P<pk>\d+)$', PendingComandaCloseView.as_view(), name='pending_comanda_close'),
    url(r'^subcomanda/cancel/(?P<pk>\d+)$', PendingSubcomandaCancelView.as_view(), name='pending_subcomanda_cancel'),
    url(r'^comanda/cancel/(?P<pk>\d+)$', PendingComandaCancelView.as_view(), name='pending_comanda_cancel'),
    url(r'^comanda/detail/(?P<pk>\d+)$', ComandaDetailView.as_view(), name='comanda_detail'),
    url(r'^subcomanda/detail/(?P<pk>\d+)$', SubcomandaDetailView.as_view(), name='subcomanda_detail'),

    # Dashboard
    url(r'^dashboard/$', DashboardView.as_view() , name='dashboard'),
    url(r'^dashboard/comanda/$', DashboardComandaView.as_view() , name='dashboard_comanda'),
    url(r'^dashboard/subcomanda/$', DashboardSubcomandaView.as_view() , name='dashboard_subcomanda'),
    url(r'^dashboard/proiect/$', DashboardProiectView.as_view() , name='dashboard_proiect'),
    url(r'^dashboard/furnizor/$', DashboardFurnizorView.as_view() , name='dashboard_furnizor'),
    url(r'^dashboard/producator/$', DashboardProducatorView.as_view() , name='dashboard_producator'),
    url(r'^dashboard/reper/$', DashboardReperView.as_view(), name='dashboard_reper'),
    url(r'^dashboard/comanda/new/$', DashboardComandaCreateView.as_view(), name='dashboard_comanda_new'),
    url(r'^dashboard/comanda/edit/(?P<pk>\d+)$', DashboardComandaEditView.as_view(), name='dashboard_comanda_edit'),
    url(r'^dashboard/subcomanda/new/$', DashboardSubcomandaCreateView.as_view(), name='dashboard_subcomanda_new'),
    url(r'^dashboard/subcomanda/edit/(?P<pk>\d+)$', DashboardSubcomandaEditView.as_view(), name='dashboard_subcomanda_edit'),
   

    # Modal dialogs for dashboard
    url(r'^reper/new/$', DashboardReperCreateView.as_view() , name='reper_new'),
    url(r'^reper/edit/(?P<pk>\d+)$', DashboardReperEditView.as_view(), name='reper_edit'),
    url(r'^producator/new/$', DashboardProducatorCreateView.as_view() , name='producator_new'),
    url(r'^producator/edit/(?P<pk>\d+)$', DashboardProducatorEditView.as_view(), name='producator_edit'),
    url(r'^furnizor/new/$', DashboardFurnizorCreateView.as_view() , name='furnizor_new'),
    url(r'^furnizor/edit/(?P<pk>\d+)$', DashboardFurnizorEditView.as_view(), name='furnizor_edit'),
    url(r'^proiect/new/$', DashboardProiectCreateView.as_view() , name='proiect_new'),
    url(r'^proiect/edit/(?P<pk>\d+)$', DashboardProiectEditView.as_view(), name='proiect_edit'),
    url(r'^persoana/new/$', DashboardPersoanaCreateView.as_view() , name='persoana_new'),
    url(r'^reper/view/$', DashboardReperModalView.as_view(), name='reper_view'),
   
    # History 
    url(r'^history$', HistoryView.as_view(), name='history'),   

    # # Search
    # url(r'^search$', SearchView.as_view(), name='search'),  
     
    url(r'^search/(?P<cod_reper_text>[ \w ]+)/(?P<reper_text>[ \w ]+)/(?P<furnizor_text>[ \w ]+)/(?P<proiect_text>[ \w ]+)/(?P<obiect_text>[ \w ]+)$', SearchView.as_view(), name='search'),
   
    
]

orderhelper/models.py
from django.db import models
from django.utils import timezone
from django.utils.timezone import now
from datetime import date, timedelta
from django.contrib.auth.models import Group

class Valuta(models.Model):
	DOLLARS = 'USD'
	EURO = 'EURO'
	RON = 'RON'

	VALUTA_CHOICES = (
		(DOLLARS, 'USD'),
		(EURO, 'EURO'),
		(RON, 'RON'),
	)
	text = models.CharField(max_length=5, choices=VALUTA_CHOICES, default=RON)

	def __str__(self):
		return self.text 

class Status(models.Model):
	DESCHIS = 'Deschis'
	INCHIS = 'Inchis'
	ANULAT = 'Anulat'

	STATUS_CHOICES = (
		(DESCHIS, 'Deschis'),
		(INCHIS, 'Inchis'),
		(ANULAT, 'Anulat'),
	)

	text = models.CharField(max_length=20, choices=STATUS_CHOICES, default=DESCHIS)

	def __str__(self):
		return self.text

class Persoana(models.Model):
	nume = models.CharField('Nume', max_length=100)
	prenume = models.CharField('Prenume', max_length=100)
	telefon = models.CharField('Telefon', max_length=10, blank=True, null=True)
	group = models.ManyToManyField(Group, related_name='persoanas')

	def __str__(self):
		return self.nume + ' ' + self.prenume;

class Proiect(models.Model):
	titlu = models.CharField('Denumire', blank=False, null=False, max_length=255)
	descriere = models.TextField('Descriere', blank=True, null=True)
	group = models.ManyToManyField(Group,blank=False, null=False, related_name='proiects')

	def __str__(self):
		return self.titlu

class Producator(models.Model):
	nume = models.CharField('Nume', max_length=255)
	descriere = models.TextField('Descriere', blank=True, null=True)
	telefon = models.CharField('Telefon', max_length=10, blank=True, null=True)
	group = models.ManyToManyField(Group, related_name='producators')

	def __str__(self):
		return self.nume

class Furnizor(models.Model):
	nume = models.CharField('Nume', max_length=255)
	descriere = models.TextField('Descriere', blank=True, null=True)
	telefon = models.CharField('Telefon', max_length=10, blank=True, null=True)
	group = models.ManyToManyField(Group, related_name='furnizors')

	def __str__(self):
		return self.nume

class TermenPlata(models.Model):
	tip = models.CharField('Tip termen', max_length=50)

	def __str__(self):
		return self.tip

class ModPlata(models.Model):
	tip = models.CharField('Mod plata', max_length=50)

	def __str__(self):
		return self.tip

class Reper(models.Model):
	cod_reper = models.CharField('Cod reper', max_length=100, null=True)
	reper = models.TextField('Reper',null=True)
	link = models.URLField('Link',blank=True,null=True)
	group = models.ManyToManyField(Group, related_name='repers')

	def __str__(self):
		return self.cod_reper

class Subcomanda(models.Model):
	comanda_ref = models.ForeignKey('Comanda', null=True, verbose_name='Comanda') 
	numar_curent = models.IntegerField('Numar Curent',null=True)
	status = models.ForeignKey('Status',null=True)
	producator = models.ForeignKey('Producator',blank=True, null=True)
	reper = models.ForeignKey('Reper', null=True)
	furnizor = models.ForeignKey('Furnizor', null=True)
	cantitate = models.DecimalField('Cantitate', default=0, max_digits=9, decimal_places=0, null=True)
	data_livrare = models.DateField('Data livrare',null=True)
	data_primire = models.DateField('Data primire',blank=False, null=True)
	pret = models.DecimalField('Pret', default=0, max_digits=9, decimal_places=2, null=True)
	valuta = models.ForeignKey('Valuta', null=True, verbose_name='Valuta')
	data = models.DateField('Data',default=now())

	def set_pret_total(self):
		return self.pret * self.cantitate

	pret_total = property(set_pret_total)
	termen_plata = models.ForeignKey('TermenPlata', null=True)
	mod_plata = models.ForeignKey('ModPlata', null=True)
	group = models.ManyToManyField(Group, related_name='subcomandas')

	def is_late(self):
		if self.status.text != 'Deschis':
			return False
		return date.today().isoformat() > self.data_livrare.isoformat()

	def is_today(self):
		if self.status.text != 'Deschis':
			return False
		return date.today().isoformat() == self.data_livrare.isoformat()	

	def __str__(self):
		return 'Subcomanda: ' + str(self.numar_curent)


class Comanda(models.Model):
	status = models.ForeignKey('Status', null=True)
	data = models.DateField('Data',default=now())
	obiect_succint = models.TextField('Obiect Succint', null=True)
	solicitant = models.ForeignKey('Persoana',null=True, verbose_name='Solicitant')
	# cc = models.ForeignKey('Persoana', null=True, blank=True, verbose_name='CC')
	preluat = models.ForeignKey('auth.User', verbose_name='Preluare', null=True)
	proiect = models.ForeignKey('Proiect', null=True)

	def set_pret_total(self):
		subcomenzi = Subcomanda.objects.exclude(status__text='Anulat').filter(comanda_ref__pk=self.pk)
		total = 0
		for subcomanda in subcomenzi:
			total += subcomanda.pret_total
		return total

	pret_total = property(set_pret_total)
	data_primire = models.DateField('Data primire',blank=False, null=True)
	group = models.ManyToManyField(Group, related_name='coamandas')


	def is_late(self):
		subcomenzi = Subcomanda.objects.all().filter(comanda_ref__pk=self.pk, status__text='Deschis')
		for subcomanda in subcomenzi:
			if date.today().isoformat() > subcomanda.data_livrare.isoformat():
				return True
		return False

	def is_today(self):
		subcomenzi = Subcomanda.objects.all().filter(comanda_ref__pk=self.pk, status__text='Deschis')
		for subcomanda in subcomenzi:
			if date.today().isoformat() == subcomanda.data_livrare.isoformat():
				return True
		return False

	def calculate_progress(self):
		subcomenzi_total = Subcomanda.objects.exclude(status__text='Anulat').filter(comanda_ref__pk=self.pk).count()
		subcomenzi_finished = Subcomanda.objects.all().filter(comanda_ref__pk=self.pk,status__text='Inchis').count()
		if subcomenzi_total == 0:
			return 0
		return ( subcomenzi_finished * 100 ) / subcomenzi_total

	def show_subcomenzi(self):
		return Subcomanda.objects.all().filter(comanda_ref__pk=self.pk)

	def show_valuta(self):
		return	Subcomanda.objects.filter(comanda_ref__pk=self.pk).latest('pk').valuta
		
	def __str__(self):
		return 'Comanda: ' + str(self.pk)

orderhelper/forms.py
from django import forms
from django.forms import HiddenInput
from datetimewidget.widgets import DateWidget
from .models import Persoana, Proiect, Furnizor, Producator, Reper, Comanda, Subcomanda, Valuta
from datetime import date, datetime, timedelta
from django.utils.timezone import now

class PersoanaForm(forms.ModelForm):

    class Meta:
        model = Persoana
        fields = ('nume', 'prenume', 'telefon','group',)
        widgets = {
			'nume': forms.TextInput(attrs={'class': 'form-control'}),
			'prenume': forms.TextInput(attrs={'class': 'form-control'}),
			'telefon': forms.TextInput(attrs={'class': 'form-control'}),
            'group': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }
 
class ProiectForm(forms.ModelForm):

	class Meta:
		model = Proiect
		fields = ('titlu','descriere','group',)
		widgets = {
			'titlu': forms.TextInput(attrs={'class': 'form-control'}),
			'descriere': forms.TextInput(attrs={'class': 'form-control'}),
            'group': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

class FurnizorForm(forms.ModelForm):

	class Meta:
		model = Furnizor
		fields = ('nume','descriere','telefon','group',)
		widgets = {
			'nume': forms.TextInput(attrs={'class': 'form-control'}),
			'descriere': forms.TextInput(attrs={'class': 'form-control'}),
			'telefon': forms.TextInput(attrs={'class': 'form-control'}),
            'group': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

class ProducatorForm(forms.ModelForm):

	class Meta:
		model = Producator
		fields = ('nume','descriere','telefon','group',)
		widgets = {
			'nume': forms.TextInput(attrs={'class': 'form-control'}),
			'descriere': forms.TextInput(attrs={'class': 'form-control'}),
			'telefon': forms.TextInput(attrs={'class': 'form-control'}),
            'group': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

class ReperForm(forms.ModelForm):

	class Meta:
		model = Reper
		fields = ('cod_reper','reper','link','group',)
		widgets = {
			'cod_reper': forms.TextInput(attrs={'class': 'form-control'}),
			'reper': forms.TextInput(attrs={'class': 'form-control'}),
			'link': forms.TextInput(attrs={'class': 'form-control'}),
            'group': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

class ComandaForm(forms.ModelForm):

	class Meta:
		model = Comanda
		fields = ('obiect_succint','solicitant','proiect','group',)
		widgets = {
			'obiect_succint': forms.TextInput(attrs={'class': 'form-control'}),
			'solicitant': forms.Select(attrs={'class': 'form-control'}),
			'proiect': forms.Select(attrs={'class': 'form-control'}),
            'group': forms.SelectMultiple(attrs={'class': 'form-control'}),
		}

class ComandaEditForm(forms.ModelForm):

	class Meta:
		model = Comanda
		dateOptions = {
			'format': 'mm/dd/yyyy',
			'autoclose': True
		}
		fields = ('status','obiect_succint','solicitant','proiect','data','group',)
		widgets = {
			'status': forms.Select(attrs={'class': 'form-control'}),
			'obiect_succint': forms.TextInput(attrs={'class': 'form-control'}),
			'solicitant': forms.Select(attrs={'class': 'form-control'}),
			'proiect': forms.Select(attrs={'class': 'form-control'}),
			'data': DateWidget(attrs={'id':"iddata"}, bootstrap_version=3, options = dateOptions),
            'group': forms.SelectMultiple(attrs={'class': 'form-control'}),
		}

class SubcomandaForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super(SubcomandaForm, self).__init__(*args, **kwargs)
		self.fields['comanda_ref'].queryset = Comanda.objects.filter(status__text='Deschis').order_by('-pk')

	class Meta:
		model = Subcomanda
		fields = ('comanda_ref','producator','reper','furnizor','cantitate','pret','valuta','termen_plata','mod_plata','data_livrare','group',)
		dateOptions = {
			'format': 'mm/dd/yyyy',
			'autoclose': True
		}
		widgets = {
			'comanda_ref': forms.Select(attrs={'class': 'form-control'}),
			'producator': forms.Select(attrs={'class': 'form-control'}),
			'reper': forms.Select(attrs={'class': 'form-control'}),
			'furnizor': forms.Select(attrs={'class': 'form-control'}),
			'cantitate': forms.NumberInput(attrs={'class': 'form-control'}),
			'pret': forms.NumberInput(attrs={'class': 'form-control'}),
			'valuta': forms.Select(attrs={'class': 'form-control'}),
			'termen_plata': forms.Select(attrs={'class': 'form-control'}),
			'mod_plata': forms.Select(attrs={'class': 'form-control'}),
			'data_livrare': DateWidget(attrs={'id':"idlivrare"}, bootstrap_version=3, options = dateOptions),
            'group': forms.SelectMultiple(attrs={'class': 'form-control'}),
		}

class SubcomandaEditForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super(SubcomandaEditForm, self).__init__(*args, **kwargs)
		self.fields['comanda_ref'].queryset = Comanda.objects.filter(status__text='Deschis')

	class Meta:
		model = Subcomanda
		fields = ('comanda_ref','status','producator','reper','furnizor','cantitate','pret','valuta','termen_plata','mod_plata','data_livrare','group',)
		dateOptions = {
			'format': 'mm/dd/yyyy',
			'autoclose': True
		}
		widgets = {
			'comanda_ref': forms.Select(attrs={'class': 'form-control'}),
			'status': forms.Select(attrs={'class': 'form-control'}),
			'producator': forms.Select(attrs={'class': 'form-control'}),
			'reper': forms.Select(attrs={'class': 'form-control'}),
			'furnizor': forms.Select(attrs={'class': 'form-control'}),
			'cantitate': forms.NumberInput(attrs={'class': 'form-control'}),
			'pret': forms.NumberInput(attrs={'class': 'form-control'}),
			'valuta': forms.Select(attrs={'class': 'form-control'}),
			'termen_plata': forms.Select(attrs={'class': 'form-control'}),
			'mod_plata': forms.Select(attrs={'class': 'form-control'}),
			'data_livrare': DateWidget(attrs={'id':"idlivrare"}, bootstrap_version=3, options = dateOptions),
            'group': forms.SelectMultiple(attrs={'class': 'form-control'}),
		}

class SubcomandaCloseForm(forms.ModelForm):
	
	def __init__(self, *args, **kwargs):
		super(SubcomandaCloseForm, self).__init__(*args, **kwargs)
		self.fields['data_primire'].initial = datetime.now()

	class Meta:
		model = Subcomanda
		fields = ('data_primire',)
		dateOptions = {
			'format': 'mm/dd/yyyy',
			'autoclose': True
		}
		widgets = {
			'data_primire': DateWidget(attrs={'id':"idprimire"}, bootstrap_version=3, options = dateOptions),
		}

class ComandaCloseForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super(ComandaCloseForm, self).__init__(*args, **kwargs)
		self.fields['data_primire'].initial = datetime.now()

	class Meta:
		model = Comanda
		fields = ('data_primire',)
		dateOptions = {
			'format': 'mm/dd/yyyy',
			'autoclose': True
		}
		widgets = {
			'data_primire': DateWidget(attrs={'id':"idprimire"}, bootstrap_version=3, options = dateOptions),
		}

orderhelper/templates/orderhelper/_pagination.html
{% load i18n %}
<nav>
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li><a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a></li>
    {% else %}
        <li class="disabled"><span class="disabled prev">&lsaquo;&lsaquo; {% trans "previous" %}</span></li>
    {% endif %}
    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active"><span class="sr">{{ page }}</span></li>
            {% else %}
                <li><a href="?{{ page.querystring }}" class="page"> {{ page }}</a></li>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li><a href="?{{ page_obj.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a></li>
    {% else %}
        <li class="disabled"><span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span></li>
    {% endif %}
</ul>
</nav>

orderhelper/templates/orderhelper/comanda_all.html
{% extends 'orderhelper/base.html' %}

{% block content %}
  {% if user.is_authenticated %}
	<h1 class="sub-header">Dashboard - <em> Comanda </em> </h1>

	<br /> <br />
	<div class="btn-group" role="group" aria-label="...">
 		<a href="{% url 'comanda_new' %}" type="button" class="btn btn-primary">Add</a>
  		<button type="button" id="edit" class="btn btn-default disabled">Edit</button>
  		<button  type="button" class="btn btn-default disabled">Delete</button>
	</div>
	<br /> <br />
	<hr class="featurette-divider">

	<div class="table-responsive">
		<table class="table">
		    <thead>
			    <tr>
			    	<th></th>
			    	<th>ID</th>
			        <th>Numar unic</th>
			        <th>Data</th>
			        <th>Obiect succint</th>
			        <th>Solicitant</th>
			        <th>Preluat</th>
			        <th>Proiect</th>
 				</tr>
		    </thead>
		    <tbody>
		              
			{% for comanda in comenzi %}			
			<tr>         
				<td><input type="checkbox" url="{%  url 'comanda_edit' pk=comanda.pk  %}" aria-label="select"></td> 
			    <td>{{ comanda.pk }}</td>
				<td>{{ comanda.numar_unic }}</td>
				<td>{{ comanda.data }}</td>
				<td>{{ comanda.obiect_succint }}</td>
				<td>{{ comanda.solicitant }}</td>
				<td>{{ comanda.preluat }}</td>
				<td>{{ comanda.proiect }}</td>
			</tr>
			{% endfor %}
			</tbody>
		</table>     	
	</div>

	<script>
		$(document).ready(function(){

			var url;

			// Make call to edit 
	        $("#edit").click(function(){
				$(location).attr('href', url );
			});

	        // Get the checkboxes
	        $( "input" ).on( "click", function() {
	        	url = $( "input:checked" ).attr('url');

	        	$("#edit").removeClass('disabled')
	        	if ( $( "input:checked" ).length > 1 || $( "input:checked" ).length == 0 ) {
	        		$("#edit").addClass('disabled')	
	        	}	
			});
	    });
    
	</script>	


  {% endif %}
{% endblock %}

orderhelper/templates/orderhelper/comanda_close.html
{% load staticfiles %}

<div class="modal-dialog">
    <div class="modal-content">
	    <form method="POST" action="{% url 'comanda_close' pk=comanda.pk %}" id="comanda_close" class="comanda-form" >{% csrf_token %}
	    	  {{ form.media }}
	    	<div class="modal-header">

		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title">Inchide comanda</h4>
	      	</div>
	      	<div class="modal-body">
	      		<div class="row">
          			<div class="col-md-6">
	        			{{ form.as_p }}
	        		</div>
	        	</div>		
	      	</div>
	      	<div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		        <button type="submit" class="btn btn-primary">Save changes</button>
	      	</div>
	    </form>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->

<script>

	$(document).ready(function(){
	    $("#idprimire").datetimepicker({
			format: 'mm/dd/yyyy'})
	});

    var form_options = { target: '#modalClose', success: function(response) {} };
    $('#subcomanda_close').ajaxForm(form_options);
</script>
<script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="{% static 'js/moment.js' %}"></script> 
<script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>  

orderhelper/templates/orderhelper/dashboard_subcomanda_new.html
{% extends 'orderhelper/base.html' %}
{% load staticfiles %}

{% block extra_js%}
<script src="http://malsup.github.com/jquery.form.js"></script>
{% endblock %}


{% block content %}
  {% if user.is_authenticated %}
	<h1 class="sub-header">Dashboard <small> Adauga subcomanda </small>  </h1>

	{% if messages %}
	<div class="messages">
    	{% for message in messages %}
	    	{% if message.level == 20 %}
	    		<div class="alert alert-success" role="alert"><span class="glyphicon glyphicon-info-sign"></span> {{ message }}</div>
	    	{% else %}
	    		<div class="alert alert-danger" role="alert"><span class="glyphicon glyphicon-warning-sign"></span> {{ message }}</div>
	    	{% endif %}
   		{% endfor %}
	</div>
	{% endif %}

	 <br />
	
	<br />
	 <form method="POST" class="proiect-form">{% csrf_token %}
	     {{ form.media }}
	    <div class="row">
          	<div class="col-md-6">

	        	{{ subcomandaform.as_p }}
	        </div>
	        <div class="col-md-2"></div>
	         <div id="bubble" class="col-md-2 placeholder">
             	<a type="button" class="actionAdd" data-toggle="modal" data-target="#modal" href="{% url 'producator_new' %}">  <img src="{% static 'img/producator.jpg' %}" width="130" height="130" class="img-responsive" alt="Generic placeholder thumbnail"></a>
              <h4><span class="glyphicon glyphicon-plus-sign"> Producator</span></h4>
          
            </div>
            <div id="bubble" class="col-md-2 placeholder">
              <a type="button" class="actionAdd" data-toggle="modal" data-target="#modal" href="{% url 'furnizor_new' %}"> <img src="{% static 'img/furnizor.jpg' %}" width="130" height="130" class="img-responsive" alt="Generic placeholder thumbnail"></a>
                <h4><span class="glyphicon glyphicon-plus-sign"> Furnizor</span></h4>
             
            </div>
             <div class="col-md-2"></div>
             <div id="bubble" class="col-md-2 placeholder">
            	<a type="button" class="actionAdd" data-toggle="modal" data-target="#modal" href="{% url 'reper_new' %}"> <img src="{% static 'img/reper.jpg' %}" width="130" height="130" class="img-responsive" alt="Generic placeholder thumbnail"></a>
                <h4><span class="glyphicon glyphicon-plus-sign"> Reper</span></h4>
            </div>

            <div class="col-md-2"></div>
            	<div id="bubble" class="col-md-2 placeholder">
            		<a type="button" class="actionAdd" data-toggle="modal" data-target="#modal" href="{% url 'reper_view' %}"> <img src="{% static 'img/view_reper.jpg' %}" width="130" height="130" class="img-responsive" alt="Generic placeholder thumbnail"></a>
                	<h4><span class="glyphicon glyphicon-eye-open"> Reper</span></h4>
            </div>
	    </div>		
	     
	     <hr class="featurette-divider">
	     
	    <div class="row"> 
	      	<div class="col-md-6">
	      		<a type="button" href="{% url 'dashboard_subcomanda' %}" class="btn btn-default">Cancel</a>
		        <button type="submit" class="btn btn-primary">Save changes</button>
		    </div>
		</div>
	      	
	    </form>

<div class="modal fade" id="modal"></div>
	
<script>
	$(document).ready(function(){
		$("#idlivrare").datetimepicker({
			format: 'mm/dd/yyyy'});

	    $("#id_cantitate").val(1);
	});
</script>

<!-- Keep scripts in this order 1. dashboard.js / 2. ajaxModal.js --> 
<script src="{% static 'js/dashboard.js' %}"></script>
<script src="{% static 'js/ajaxModal.js' %}"></script>

  {% endif %}
{% endblock %}